# Generated by Django 2.1 on 2018-08-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairschool', '0002_auto_20180802_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='username',
            new_name='id',
        ),
    ]
