# Generated by Django 2.1 on 2018-08-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairschool', '0003_auto_20180802_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='name',
            new_name='full_name',
        ),
    ]
