# Generated by Django 2.0.7 on 2018-08-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stylist', models.CharField(max_length=30)),
                ('Service', models.CharField(max_length=30)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Time', models.DateTimeField()),
                ('Consultation', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three')], default=3)),
                ('On_time', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three')], default=3)),
                ('Styling', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three')], default=3)),
                ('Customer_Service', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three')], default=3)),
                ('Overall', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three')], default=3)),
                ('Notes', models.CharField(max_length=300)),
            ],
        ),
    ]
