# Generated by Django 2.1 on 2018-08-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairschool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_feedback',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='user_feedback',
            old_name='Notes',
            new_name='overallFeedback',
        ),
        migrations.RenameField(
            model_name='user_feedback',
            old_name='Service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='user_feedback',
            old_name='Stylist',
            new_name='stylist',
        ),
        migrations.RemoveField(
            model_name='user_feedback',
            name='Consultation',
        ),
        migrations.RemoveField(
            model_name='user_feedback',
            name='Customer_Service',
        ),
        migrations.RemoveField(
            model_name='user_feedback',
            name='On_time',
        ),
        migrations.RemoveField(
            model_name='user_feedback',
            name='Overall',
        ),
        migrations.RemoveField(
            model_name='user_feedback',
            name='Styling',
        ),
        migrations.RemoveField(
            model_name='user_feedback',
            name='Time',
        ),
        migrations.AddField(
            model_name='user_feedback',
            name='consultationRating',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3),
        ),
        migrations.AddField(
            model_name='user_feedback',
            name='customerServiceRating',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3),
        ),
        migrations.AddField(
            model_name='user_feedback',
            name='overallRating',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3),
        ),
        migrations.AddField(
            model_name='user_feedback',
            name='stylingRating',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3),
        ),
        migrations.AddField(
            model_name='user_feedback',
            name='timeRating',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3),
        ),
    ]
