# Generated by Django 2.1 on 2018-08-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairschool', '0002_auto_20180809_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_feedback',
            name='consultationRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='customerServiceRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='overallRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='stylingRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='timeRating',
            field=models.IntegerField(),
        ),
    ]
